networks:
  mangabaka-network:
    driver: bridge

services:
  postgresql:
    container_name: mangabaka-postgresql
    image: postgres:alpine3.16
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - ../../backend/src/main/resources/docker/sql:/docker-entrypoint-initdb.d
    networks:
      - mangabaka-network
    restart: always

  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: mangabaka
    depends_on:
      - postgresql
    environment:
      BACKEND_MODE: ${BACKEND_MODE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_JDBC_URL: ${PG_JDBC_URL}
    ports:
      - "9090:9090"
    volumes:
      - ~/docker:/app/data/mangabaka
    networks:
      - mangabaka-network
    restart: always
