networks:
  mangabaka-network:
    driver: bridge

services:
  postgresql:
    container_name: mangabaka-postgresql
    image: postgres:alpine3.16
    environment:
      POSTGRES_DB: ${PG_DB_NAME_PROD}
      POSTGRES_PASSWORD: ${PG_PASSWORD_PROD}
      POSTGRES_USER: ${PG_USERNAME_PROD}
    ports:
      - "5432:5432"
    volumes:
      - ../backend/src/main/resources/docker/sql:/docker-entrypoint-initdb.d
    networks:
      - mangabaka-network
    restart: always

  jetty:
    image: jetty:12.0.22-jdk17
    container_name: mangabaka-jetty
    depends_on:
      - postgresql
    ports:
      - "9090:9090"
    volumes:
      - ../backend/build/libs/backend.war:/var/lib/jetty/webapps/ROOT.war
      - ../backend/.env:/var/lib/jetty/.env
    command: >
      --module=ee10-deploy,ee10-webapp,http,ee10-annotations,ee10-servlet
      -Djetty.http.port=9090
      -Djetty.deploy.scanInterval=10
    networks:
      - mangabaka-network
    restart: always