services:
  jetty:
    image: jetty:12.0.22-jdk17
    container_name: mangabaka-jetty
    ports:
      - "9090:8080"
    volumes:
      - ../backend/build/libs/backend.war:/var/lib/jetty/webapps/ROOT.war
    command: >
      --module=ee10-deploy,ee10-webapp,http,ee10-annotations,ee10-servlet
      -Djetty.deploy.scanInterval=10
      -Djetty.webapp.addServerClasses=org.eclipse.jetty.server.webapp.WebInfConfiguration
    restart: always